name: Release Snapshot

on:
  workflow_dispatch:

jobs:

  jar:
    runs-on: ubuntu-latest
    name: Build Jar
    steps:
      - uses: actions/checkout@v2
        with:
          repository: rd-1-2022/spring-up
      - run: ./gradlew build --no-daemon
      - uses: actions/upload-artifact@v2
        with:
          name: spring-up-jar
          path: build/libs/
          retention-days: 1

  native:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - nickname: macos
            os: macos-latest
            graal: 22.0.0.2
          - nickname: linux-ubuntu20
            os: ubuntu-20.04
            graal: 22.0.0.2
          - nickname: linux-ubuntu18
            os: ubuntu-18.04
            graal: 22.0.0.2
    name: Build ${{ matrix.nickname }}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: rd-1-2022/spring-up
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
          cache: gradle
      - uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ matrix.graal }}
          java-version: 11
          components: native-image
          set-java-home: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: ./gradlew build nativeCompile --no-daemon
      - uses: actions/upload-artifact@v2
        with:
          name: spring-up-${{ matrix.nickname }}
          path: build/native/nativeCompile/
          retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: [native,jar]
    name: Release
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: spring-up-macos
          path: build/download/spring-up-macos
      - uses: actions/download-artifact@v2
        with:
          name: spring-up-linux-ubuntu20
          path: build/download/spring-up-linux-ubuntu20
      - uses: actions/download-artifact@v2
        with:
          name: spring-up-linux-ubuntu18
          path: build/download/spring-up-linux-ubuntu18
      - uses: actions/download-artifact@v2
        with:
          name: spring-up-jar
          path: build/download/spring-up-jar
      - name: Prepare Release
        run: |
          echo TAG=$(date +%Y%m%d-%H%m%S) >> $GITHUB_ENV
          mkdir build/upload
          mv build/download/spring-up-linux-ubuntu18/spring-up build/upload/spring-up-linux-ubuntu18
          mv build/download/spring-up-linux-ubuntu20/spring-up build/upload/spring-up-linux-ubuntu20
          mv build/download/spring-up-macos/spring-up build/upload/spring-up-darwin-amd64
          mv build/download/spring-up-jar/spring-up-*-SNAPSHOT.jar build/upload/
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.TAG }}
          prerelease: true
          artifacts: "build/upload/*"
          token: ${{ secrets.GITHUB_TOKEN }}
